### ISSUE TITLE
OCP 4.2 Install Improvement: Check file server

### ISSUE THREAD

**Issue by jristow** [mrislam11378/OCP4.x-and-icp4i-install#1]
After running the ignition creation, append-bootstrap portion we should add a note to check if they can access their bootstrap.ign file hosted on their webserver. Some people have been having issues with file permissions on the webserver and this is a good check before they turn on their vm's.
to change the bootstrap.ign file permissions they should run `chmod go+r bootstrap.ign` from their cluster directory.

**Comment by mrislam11378** [comment]
okay, not a bad idea. I usually just go the the append bootstrap source url from the browser (i.e. http://172.18.*.*/mislam/bootstrap.ign) from the browser and see if the ignition file comes up
